version: "3.8"

services:
  optibot:
    build: .
    env_file: .env
    volumes:
      - ./articles:/app/articles
      - ./logs:/app/logs
    command: ["cron", "--limit", "30", "--priority", "youtube"]
    restart: "no"

  optibot-web:
    build: .
    env_file: .env
    volumes:
      - ./articles:/app/articles
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    command: []
    restart: "unless-stopped"
